### PR TITLE
10 add export feature

### LINKED ISSUE #10: Add export feature
When viewing a single repository's data, add an **Export* button that prepares a comma-separated file (.csv) for download with the format:

First row should have the following column headers (in **bold**) and the accompanying explanations of describe what values the column should hold. After the first (header) row, each subsequent row should represent a single action. When an action does not have data for that particular column, it should default to `NA`:

* **Repository** - stores the name of the repository, as extracted from the URL (i.e. `https://github.com/ChicoState/PantryNode` should be represented as `PantryNode`)
* **Timestamp** 
* **Action** - one of the following values, according to which action was taken: `commit`, `issue`, `pull_request`, `code_review`, `comment`
* **Author** -  the author of a commit or otherwise the primary actor on the action
* **Repo_ID** - the ID number (e.g. Issue `#1` should be `1`), or `NA` if not an action that has a dedicated number
* **Additions** - lines added in a commit, or `NA` if not a commit
* **Deletions** - lines deleted in a commit, or `NA` if not a commit
* **Message** - text of the message for any of the actions, or `NA` if not applicable
* **Assignees** - a list of anyone assigned to an issue, with each username separated by a semi-colon `;`
* **Close_date** - timestamp of when the issue or pull request was closed
* **Closed_by** - username of person who closed an issue or pull request
* **Request_Status** - one of the values that represents the status of a PR (`approved`, `open`, or `closed`)
* **Reviewers** - a list of anyone who reviewed a pull request, with each username separated by a semi-colon `;`
* **Review_Recommendation** - one of the values that represents the recommendation of a code review (`comment`, `approve`, or `request changes`)
* **Tagged** - the ID number (e.g. Issue \#1 should be `1`) of a tagged issue/pull request if is has been associated with the action. This is *not* the ID of the action itself, but rather, if the action tags another ID. For example, if PR \#4 closes issues \#1, then this value should be `1`.

### PR DESCRIPTION
**Pull request by rahulbijoor**
I have added export data feature which stores the data in downloadable file in csv format and reduced the number of API calls needed to retrieve the data.

### CODE REVIEW

**Review by kbuffardi — CHANGES_REQUESTED** [review]
I ran it on my machine with `BudgetTravel` repo and it seemed to record the **commits**, **pull requests**, and a **comment**. However, the exported data seemed to be missing:

- [ ] No **issues** were logged, but in retrospect I found the repo did not have any issues for some reason. Based on this repo, I can't confirm or deny that issues are recording correctly.
- [ ] No **code_reviews** were logged. I confirmed that the repos PRs typically had 2 reviews
- [ ] `additions` and `deletions` columns are still missing for all commits

At least for this repo, the username (author) logging seems consistent.

**Comment by kbuffardi** [comment]
@rahulbijoor one more thought -- is this using a private API key? I perused the repo and didn't see one in the commits (which is a good thing) but I thought GitHub required a key to track our API calls. If so, please include in the `README.md` instructions what the variable name should be and where it should be stored/set, and remove it from the repo. If not, you can just clarify in a comment here.

**Comment by rahulbijoor** [comment]
@kbuffardi We are using unauthenticated requests and there is no need of API Key. However we could increase the rate limit by using API Key. For unauthenticated requests, GitHub API enforces rate limiting based on the IP address of the client making the requests.

**Comment by MSS-Shalavritha** [comment]
> * No **issues** were logged

Hi @kbuffardi, I just checked with my HotSpots repo, I see issues are being captured in the .csv file. But, code reviews, additions and deletions are not being logged.

**Comment by TJSidhu1** [comment]
> I ran it on my machine with `BudgetTravel` repo and it seemed to record the **commits**, **pull requests**, and a **comment**. However, the exported data seemed to be missing:
> 
> * [ ]  No **issues** were logged, but in retrospect I found the repo did not have any issues for some reason. Based on this repo, I can't confirm or deny that issues are recording correctly.
> * [ ]  No **code_reviews** were logged. I confirmed that the repos PRs typically had 2 reviews
> * [ ]  `additions` and `deletions` columns are still missing for all commits
> 
> At least for this repo, the username (author) logging seems consistent.

@kbuffardi My repo only shows commits but then i rechecked and there are no issues and pull requests in this repo. The additions and deletions are not being logged either.

**Pull request merged**
