### PR TITLE
Synchronize data retrieval

### PR DESCRIPTION
**Pull request by rahulbijoor**
This pull request deals with most of the issues with data retrieval process.

It makes sure that all the data is collected before user can view the data.
If the user chooses a different repo after searching for an initial repo it deletes the data of the previous repo.

I have also replaced unauthenticated requests to authenticated requests as we will need more api calls as we are running a loop  in which each individual pull request is searched for code review. 

To run the application  

- Create a  Github token  by navigating to Settings > Developer Settings > Personal Access Tokens.
- On clicking Personal Access Token you get a drop down menu choose Token(classic) option .
- In Personal access tokens (classic) page Click on Generate new token button.
- Enter a note for your token and at the end of the page click on Generate token button.
- Now you can see an alphaNumeric code on your screen,
- Copy the code and paste in the "your_github_token_here" in line 21 of GithubRepos.js

### CODE REVIEW

**Comment by kbuffardi** [comment]
@MSS-Shalavritha can you review this and verify whether it works locally for you, now that your PR has been merged?

**Comment by MSS-Shalavritha** [comment]
Sure @kbuffardi, will review it.

**Comment by MSS-Shalavritha** [comment]
@kbuffardi @rahulbijoor, tested the code, it is working for few repositories, but it isn't working for few repositories like HotSpots and Assisttop. Attached the screenshot for reference.
Screenshot 2024-06-07 at 9 52 57 AM

**Comment by rahulbijoor** [comment]
@MSS-Shalavritha I have tried fixing the issue for HotSpots and Assistop do review it.

**Comment by MSS-Shalavritha** [comment]
@rahulbijoor, tested the code, everything works fine now, able to search for repositories like Assistop and HotSpots now. If we are not making any other changes to the code, I think we can merge this PR.
Screenshot 2024-06-09 at 11 55 22 AM

**Review by kbuffardi — CHANGES_REQUESTED** [review]
I'm getting these warnings/errors when trying any repo now:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ react-dom.development.js:86

Failed to load resource: the server responded with a status of 401 ()
```

Then nothing is loaded.

**Comment by rahulbijoor** [comment]
@kbuffardi I think 401 error is due to Invalid Token. We need to create a github token as specified in the first comment and then copy it in the the line 21 of GithubRepos.js file.

> To run the application
> 
> * Create a  Github token  by navigating to Settings > Developer Settings > Personal Access Tokens.
> * On clicking Personal Access Token you get a drop down menu choose Token(classic) option .
> * In Personal access tokens (classic) page Click on Generate new token button.
> * Enter a note for your token and at the end of the page click on Generate token button.
> * Now you can see an alphaNumeric code on your screen,
> * Copy the code and paste in the "your_github_token_here" in line 21 of GithubRepos.js

**Comment by kbuffardi** [comment]
> @kbuffardi I think 401 error is due to Invalid Token. We need to create a github token as specified in the first comment and then copy it in the the line 21 of GithubRepos.js file.

Thanks for clarifying, I missed that. To simplify the process, I've included the instructions for creating a token in `README.md` but have updated it so that we store the token in an environment variable and then load it in the code (rather than having to edit the code with the value). I have pushed this change to the branch.

@rahulbijoor can you pull this latest commit I made to the branch, follow the directions in the README and verify whether or not it works for you?

**Comment by rahulbijoor** [comment]
In order to access the environment variable we need to use "process.env.VARIABLE_NAME" in GitHubRepos.js file
@kbuffardi It is working properly for me now.

**Comment by kbuffardi** [comment]
> In order to access the environment variable we need to use "process.env.VARIABLE_NAME" in GitHubRepos.js file @kbuffardi It is working properly for me now.

Good catch! I made that same change but accidentally left the file out of my commit. I'm going to accept this PR and merge into main.

**Review by kbuffardi — APPROVED** [review]

**Pull request merged**
