### PR TITLE
New Code review feature added

### PR DESCRIPTION
**Pull request by MSS-Shalavritha**

### CODE REVIEW

**Comment by kbuffardi** [comment]
@MSS-Shalavritha it looks like there are conflicts in this PR. Please pull the up-to-date `main` branch and merge it into your branch manually and double-check that both the existing features and your new features still work

**Comment by MSS-Shalavritha** [comment]
Hi @kbuffardi , I have resolved the conflicts now.

**Comment by kbuffardi** [comment]
@rahulbijoor can you verify whether or not these changes work with the fixes you made with the usernames

**Comment by rahulbijoor** [comment]
I tried to pull from the code-review-feature branch but there seems to be still conflicts in the code.
Screenshot 2024-06-01 151618

**Comment by MSS-Shalavritha** [comment]
Hi @rahulbijoor, I don't see any conflicts from my end, we can connect to resolve the conflicts.
Screenshot 2024-06-01 at 8 35 01 PM

**Comment by rahulbijoor** [comment]
@kbuffardi, I connected with @MSS-Shalavritha regarding the issue, and now I am able to run the application on my end. However, I noticed a bug in the application: when the user enters the repository name, the data is automatically fetched from GitHub without clicking the search button. Additionally, the data does not include code reviews. However, when I click the search button, I am able to get the code review data.

Also, the code in GitHub is not reflecting the actual code on the local machine. Is there any way we can ensure that the code is updating properly. Perhaps we can create a new branch ?

**Comment by kbuffardi** [comment]
> @kbuffardi, I connected with @MSS-Shalavritha regarding the issue, and now I am able to run the application on my end. 

Great. I'm glad you two are coordinating together.

> However, I noticed a bug in the application: when the user enters the repository name, the data is automatically fetched from GitHub without clicking the search button. Additionally, the data does not include code reviews. However, when I click the search button, I am able to get the code review data.

Good catch. Go ahead and create a new issue to document the feature to only make an API call once the **Search** button has been pressed. That feature can be added in a new branch and PR. However, if the code review data seems to be fetching correctly once the search button is pressed, then we can approve and merge this PR.

> Also, the code in GitHub is not reflecting the actual code on the local machine. Is there any way we can ensure that the code is updating properly.

Do you mean the code for this (ChicoState/chronicle) repository? If so, everyone just needs to make sure to sync up with GitHub whenever a new PR is merged into main. That is, we should:

1. Navigate to your local directory of the repository
2. Make sure to commit or stash any changes that have been made on your current branch.
3. Checkout main: `git checkout main`
4. Sync with github's main: `git pull -u origin main`

If you want to update the branch you're working on to be up-to-date with the latest on GitHub:

1. Check out your feature branch: `git checkout feature_branch`
2. Merge from main: `git merge main`

Often, that will automatically merge the changes, but sometimes it will identify conflicts that you'll need to manually resolve.

**Comment by MSS-Shalavritha** [comment]
@kbuffardi @rahulbijoor , pushed the code again to the same branch, able to push the code successfully now.

**Review by kbuffardi — CHANGES_REQUESTED** [review]
These changes seem to re-introduce the problem we previously discussed that the `Author` in the spreadsheet sometimes represents the GitHub username, but sometimes it has their name.

For example, if we export data for `ChicoState/chronicle` some of the commits are `Kevin Buffardi` while others are `kbuffardi`. We need to fix it so it only has the username (i.e. `kbuffardi`).

**Comment by rahulbijoor** [comment]
@kbuffardi I have resolved the username issue in synchronize data retrieval branch

**Comment by kbuffardi** [comment]
> @kbuffardi I have resolved the username issue in synchronize data retrieval branch

That branch was merged into main when the PR was accepted. However, this PR is not exhibiting the proper behavior so it looks like that feature regressed when it was merged into this branch.

**Comment by rahulbijoor** [comment]
> That branch was merged into main when the PR was accepted. However, this PR is not exhibiting the proper behavior so it looks like that feature regressed when it was merged into this branch.

I noticed the issue and worked on it again today. I have resolved it again in the new branch .

**Review by kbuffardi — APPROVED** [review]

**Pull request merged**
